name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run CMake
        run: cmake .

      - name: Build backend
        run: make backend

      - name: Build frontend
        run: make frontend
